---
apiVersion: v1
kind: Service
metadata:
  name: aspen-api-service
  labels:
    app: aspen-api-service
spec:
  selector:
    app: aspen-api
  type:  ClusterIP
  ports:
  - name:  https
    port: 443
    protocol: TCP
    targetPort: 5000
