---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aspen-web
  labels:
    app: aspen-web
  annotations:
    kubernetes.io/change-cause: {{ pipelineID }}
spec:
  spec:
  replicas: {{ webMinReplicas }}
  selector:
    matchLabels:
      app: aspen-web
  template:
    metadata:
      labels:
        app: aspen-web
    spec:
      containers:
      - name: aspen-web
        image: {{ webImage }}
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_GLOBAL_ADMIN_DOMAIN
          value: aspen
        - name: REACT_APP_API_URL
          value: {{ apiUrl }}
