---
kind: Service
apiVersion: v1
metadata:
  name: aspen-web-service
  labels:
    app: aspen-web-service
spec:
  selector:
    app: aspen-web
  type:  ClusterIP
  ports:
  - name:  http
    port: 80
    protocol: TCP
    targetPort: 3000
