version: "3.7"

services:
  api:
    container_name: localdev_api
    build:
      context: ../../src/api/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 5s
      timeout: 10s
      retries: 15
    volumes:
      - assets:/assets
    #environment:
      #- SwaggerBasePath=aspen
    ports:
      - 3333:80
    networks:
      shared:
      api:
    restart: unless-stopped
    depends_on:
      api_db:
        condition: service_healthy

  api_db:
    image: postgres
    container_name: localdev_api_db
    volumes:
      - api_db:/var/lib/postgresql/data
      - ../../dev-resources/api/backup.sql:/docker-entrypoint-initdb.d/backup.sql
    environment:
      POSTGRES_DB: aspen
      POSTGRES_USER: aspen
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U aspen"]
      interval: 5s
      timeout: 1s
      retries: 5
    restart: unless-stopped
    networks:
      api:

  keycloak:
    container_name: localdev_keycloak
    build:
      context: ../../dev-resources/keycloak
    environment:
      #- KEYCLOAK_WELCOME_THEME=aspen
      - DB_VENDOR=POSTGRES
      - DB_ADDR=keycloak_db
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_SCHEMA=public
      - DB_PASSWORD=password
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - PROXY_ADDRESS_FORWARDING=true
      - KEYCLOAK_FRONTEND_URL=http://localhost/aspen/auth
    healthcheck:
      # test: ["CMD", "curl", "-f", "http://localhost:8080/aspen/auth/resources/vc52l/welcome/keycloak/img/favicon.ico"]
      test: ["CMD", "curl", "-f", "http://localhost:8080/aspen/auth/welcome-content/bug.png"]
      interval: 3s
      timeout: 1s
      retries: 15
    networks:
      shared:
      keycloak:
    restart: unless-stopped
    depends_on:
      keycloak_db:
        condition: service_healthy

  keycloak_db:
    image: postgres
    container_name: localdev_keycloak_db
    volumes:
      - keycloak_db:/var/lib/postgresql/data
      - ./keycloak.sql:/docker-entrypoint-initdb.d/backup.sql
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
      PROXY_ADDRESS_FORWARDING: "true"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak"]
      interval: 3s
      timeout: 1s
      retries: 15    
    restart: unless-stopped
    networks:
      keycloak:

  reverse_proxy:
    build:
      context: ../../
      dockerfile: ops/local_dev/reverse-proxy/Dockerfile
    container_name: localdev_reverse_proxy
    volumes:
      - assets:/assets
      - ./reverse-proxy/errorpages:/usr/share/nginx/errorpages/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/aspen/index.html"]
      interval: 3s
      timeout: 1s
      retries: 5
    ports:
      - 80:80
    networks:
      shared:
    restart: unless-stopped
    depends_on:
      keycloak:
        condition: service_healthy
      api:
        condition: service_healthy

volumes:
  keycloak_db:
  api_db:
  assets:
  home:

networks:
  shared:
  keycloak:
  api:
