version: '3.4'

services:
  database:
    image: postgres
    container_name: database
    environment:
      - POSTGRES_USER=Aspen
      - POSTGRES_PASSWORD=Aspen
      - POSTGRES_DB=admin
      - PGPASSFILE=blank
    ports:
      - 5432:5432
    expose:
      - 5432
    networks:
      internal:

  aspen.charityapi:
    image: ${DOCKER_REGISTRY-}aspencharityapi
    build:
      context: .
      dockerfile: aspen.charityapi/Dockerfile
    container_name: charityapi
    depends_on:
      - database
    environment:
      - PGPASSFILE=/.pgpass
    volumes:
      - .pgpass:/.pgpass
    ports:
       - 5000:5000
    networks:
      internal:

  aspen.globaladminapi:
    image: ${DOCKER_REGISTRY-}aspenglobaladminapi
    build:
      context: .
      dockerfile: aspen.globaladminapi/Dockerfile
    container_name: globaladminapi
    depends_on:
      - database
    environment:
      - PGPASSFILE=/.pgpass
    volumes:
      - .pgpass:/.pgpass
    ports:
       - 5001:5000
    networks:
      internal:


  charityweb:
    build:
      context: aspen.charityweb
    container_name: charityweb
    ports:
      - 3000:3000
    environment:
      - REACT_APP_GLOBAL_ADMIN_DOMAIN=aspen
      - REACT_APP_CHARITYAPI_URL=http://kubernetes.docker.internal:5000
      - REACT_APP_GLOBALADMINAPI_URL=http://kubernetes.docker.internal:5001
    networks:
      internal:
    stdin_open: true

  globaladminweb:
    build:
      context: aspen.globaladminweb
    container_name: globaladminweb
    ports:
      - 3001:3000
    environment:
      - REACT_APP_GLOBAL_ADMIN_DOMAIN=aspen
      - REACT_APP_CHARITYAPI_URL=http://kubernetes.docker.internal:5000
      - REACT_APP_GLOBALADMINAPI_URL=http://kubernetes.docker.internal:5001
    networks:
      internal:
    stdin_open: true

networks:
  internal: