name: Deploy to 'main'

env:
  AZURE_WEBAPP_NAME: 'aspen-api--jesse-warmup'
  DOTNET_VERSION: '6.0.x'
  
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: 
      name: main
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }} 
      
      - name: Build and Publish
        run: |
          dotnet restore src/api
          dotnet build src/api --configuration Release
          dotnet publish src/api -c Release -o '${{ env.DOTNET_ROOT }}/myapp' 
          
      - name: 'Deploy to Azure'
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: <publishData><publishProfile profileName="aspen-api--jesse-warmup - Web Deploy" publishMethod="MSDeploy" publishUrl="aspen-api--jesse-warmup.scm.azurewebsites.net:443" msdeploySite="aspen-api--jesse__warmup" userName="$aspen-api--jesse__warmup" userPWD="rs21ZDtaxQmnv5wslBrot0bgYLeKJDAdyycHowfbExyAmAcDb9v4rnlijcTK" destinationAppUrl="http://aspen-api--jesse-warmup.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="http://windows.azure.com" webSystem="WebSites"><databases /></publishProfile><publishProfile profileName="aspen-api--jesse-warmup - FTP" publishMethod="FTP" publishUrl="ftp://waws-prod-dm1-251.ftp.azurewebsites.windows.net/site/wwwroot" ftpPassiveMode="True" userName="aspen-api--jesse__warmup\$aspen-api--jesse__warmup" userPWD="rs21ZDtaxQmnv5wslBrot0bgYLeKJDAdyycHowfbExyAmAcDb9v4rnlijcTK" destinationAppUrl="http://aspen-api--jesse-warmup.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="http://windows.azure.com" webSystem="WebSites"><databases /></publishProfile><publishProfile profileName="aspen-api--jesse-warmup - Zip Deploy" publishMethod="ZipDeploy" publishUrl="aspen-api--jesse-warmup.scm.azurewebsites.net:443" userName="$aspen-api--jesse__warmup" userPWD="rs21ZDtaxQmnv5wslBrot0bgYLeKJDAdyycHowfbExyAmAcDb9v4rnlijcTK" destinationAppUrl="http://aspen-api--jesse-warmup.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="http://windows.azure.com" webSystem="WebSites"><databases /></publishProfile></publishData>
          package: '${{ env.DOTNET_ROOT }}/myapp'
          slot-name: warmup
