name: Deploy Staging
on:
  push:
    branches:
      - master
  workflow_dispatch:
    
jobs:
  deloy-staging:
    runs-on: self-hosted
    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: update staging containers
        run: |
          cd ops/staging
          DOCKER_BUILDKIT=1 COMPOSE_DOCKER_CLI_BUILD=1 docker-compose build --parallel --pull
          docker-compose up -d
